name: Build and deploy GH Pages
# On every push this script is executed
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.17.2
        env:
          # BUILD_DIR: .
          # Target branch
          PAGES_BRANCH: gh-pages
          # Provide personal access token
          #TOKEN: ${{ secrets.TOKEN }}
          # Or if publishing to the same repo, use the automatic token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}